# Generated by Django 4.0.5 on 2022-06-27 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SexoCliente',
            fields=[
                ('idsexo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de sexo')),
                ('nombreSexo', models.CharField(max_length=50, verbose_name='Nombre de sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('rut_cliente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='rut_cliente')),
                ('nombres_cliente', models.CharField(max_length=30, verbose_name='Nombres')),
                ('apellidos_clientes', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('correos_clientes', models.CharField(max_length=30, verbose_name='Correos')),
                ('dirreciones_clientes', models.CharField(max_length=30, verbose_name='Dirreción')),
                ('num_cel_clientes', models.CharField(max_length=30, verbose_name='Número de celular')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sexocliente', verbose_name='Sexo cliente')),
            ],
        ),
    ]
